Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
     - before
     - after
     - subject
     - subject!
     - let
     - let!

  AutoCorrect: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AndOr:
  AutoCorrect: false

Style/SignalException:
  EnforcedStyle: semantic
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 25


